server:
  port: 7779
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-replica1:8002/eureka/,http://eureka-server-replica2:8003/eureka/